version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        working_dir: '/workspace'
        environment:
            PYTHONPATH: /workspace
        volumes:
            - ..:/workspace
        command: sleep infinity